trainer:
  max_epochs: 10
data:
  batch_size: 64
model:
  hidden_size: 64
  graph_norm: TANH
  attn_norm: TANH
  attn_intermediate_size: 256
  loss_fn: bce
  top_k: 8
  num_negative_sample: 1024
  adversarial_temperature: 0.5
  attn_leaders: 700